In [70]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [36]:
from scipy import special

In [37]:
from IPython.core.display import display,HTML,Math

In [38]:
x=np.arange(1,10,1)
y=np.power(x,1/2)
#plt.plot(x,y)

In [39]:
xx=range(5)

In [40]:
xx

range(0, 5)

In [41]:
np.power(xx,2)

array([ 0,  1,  4,  9, 16])

In [42]:
%%capture Catal
def Catalan(n):
    if n==0:
        return (1)
    elif n==1:
        return (1)
    else:
        return (Catalan(n-1)*(4*n-2)/(n+1))
for n in range(4):
    display(Math("C_{"+str(n)+ "} = "+str(int(Catalan(n)))))
#nn=np.arange(2,1000,10)
#y=Catalan(nn)
#plot(nn,y,'r')

In [43]:
%%writefile output.txt
y.stdout

Overwriting output.txt


In [44]:
%store _ > Catalan.txt

Writing '_' (ndarray) to file 'Catalan.txt'.


In [45]:
Catal()

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [46]:
%%latex
$\frac{A}{B}$

<IPython.core.display.Latex object>

In [47]:
%%capture C
display(Math("\int_0^\infty f(x)\,dx"))

In [48]:
%%capture CC
display (7*8)

In [49]:
CC()

56

In [50]:
pwd

'/home/ph'

In [51]:
x = array([1,6,"hello"])

In [52]:
 for i in x:
     print(i)

1
6
hello


In [53]:
%%latex 
If $A=\int f(t)\,dt$, then 
$$\frac{A}{B}=\binom{c}{d}$$

<IPython.core.display.Latex object>

In [54]:
pwd

'/home/ph'

In [55]:
7*8

56

In [56]:
%%capture y
x=range(97,100)
for i in x:
    print(chr(i))

In [57]:
y.stdout

'a\nb\nc\n'

In [58]:
linspace(0,10,3)

array([  0.,   5.,  10.])

In [59]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [60]:
[i**2 for i in x]

[9409, 9604, 9801]

In [61]:
print(__)

[10  8  6  4  2]


In [62]:
def A(x):
    if x > 0:
        return x
    elif x < 0:
        return -x
    else:
        return 0

xx=range(-5,5)
y=[A(i) for i in xx]
print(y)
#plot(xx,y)

[5, 4, 3, 2, 1, 0, 1, 2, 3, 4]


In [63]:
def krav(N):
    K=np.zeros((N+1,N+1),dtype=int)
    for i in range(N+1):
        K[i,N]=int(special.binom(N,i)*(-1)**i)
        K[0,i]=1

    for i in range(1,N+1):
        for j in range(N,0,-1):
            K[i,j-1]=K[i-1,j-1]+K[i-1,j]+K[i,j]
    return K            

In [92]:
 for N in range(1,5):
    K =krav(N)
 # y=np.multiply(K,K)
#print(sum(y,axis=0))
    if N < 11:
        print("K[",N,"] = \n",K)

K[ 1 ] = 
 [[ 1  1]
 [ 1 -1]]
K[ 2 ] = 
 [[ 1  1  1]
 [ 2  0 -2]
 [ 1 -1  1]]
K[ 3 ] = 
 [[ 1  1  1  1]
 [ 3  1 -1 -3]
 [ 3 -1 -1  3]
 [ 1 -1  1 -1]]
K[ 4 ] = 
 [[ 1  1  1  1  1]
 [ 4  2  0 -2 -4]
 [ 6  0 -2  0  6]
 [ 4 -2  0  2 -4]
 [ 1 -1  1 -1  1]]


In [65]:
krav(2*N)[:,N]

array([ 1,  0, -1])

In [66]:
B=np.diag([int(special.binom(N,i)) for i in range(N+1)])
S=dot(K,B)
print(not numpy.any(S-S.T))
e=eig(S)
e[0]

True


array([ 1.41421356, -1.41421356])

In [87]:
N=10
sum([special.binom(N,x)**2 for x in range(N+1)]),special.binom(2*N,N)

(184756.0, 184756.0)