In [124]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [125]:
from scipy import special

In [126]:
from IPython.core.display import display,HTML,Math,Latex

In [127]:
def krav(N):
    K=np.zeros((N+1,N+1),dtype=int)
    for i in range(N+1):
        K[i,N]=int(special.binom(N,i)*(-1)**i)
        K[0,i]=1

    for i in range(1,N+1):
        for j in range(N,0,-1):
            K[i,j-1]=K[i-1,j-1]+K[i-1,j]+K[i,j]
    return K            

In [128]:
 for N in range(1,13):
     K =krav(N)
     y="K["+str(N)+"] = "
     print(y)
     print(K)

K[1] = 
[[ 1  1]
 [ 1 -1]]
K[2] = 
[[ 1  1  1]
 [ 2  0 -2]
 [ 1 -1  1]]
K[3] = 
[[ 1  1  1  1]
 [ 3  1 -1 -3]
 [ 3 -1 -1  3]
 [ 1 -1  1 -1]]
K[4] = 
[[ 1  1  1  1  1]
 [ 4  2  0 -2 -4]
 [ 6  0 -2  0  6]
 [ 4 -2  0  2 -4]
 [ 1 -1  1 -1  1]]
K[5] = 
[[  1   1   1   1   1   1]
 [  5   3   1  -1  -3  -5]
 [ 10   2  -2  -2   2  10]
 [ 10  -2  -2   2   2 -10]
 [  5  -3   1   1  -3   5]
 [  1  -1   1  -1   1  -1]]
K[6] = 
[[  1   1   1   1   1   1   1]
 [  6   4   2   0  -2  -4  -6]
 [ 15   5  -1  -3  -1   5  15]
 [ 20   0  -4   0   4   0 -20]
 [ 15  -5  -1   3  -1  -5  15]
 [  6  -4   2   0  -2   4  -6]
 [  1  -1   1  -1   1  -1   1]]
K[7] = 
[[  1   1   1   1   1   1   1   1]
 [  7   5   3   1  -1  -3  -5  -7]
 [ 21   9   1  -3  -3   1   9  21]
 [ 35   5  -5  -3   3   5  -5 -35]
 [ 35  -5  -5   3   3  -5  -5  35]
 [ 21  -9   1   3  -3  -1   9 -21]
 [  7  -5   3  -1  -1   3  -5   7]
 [  1  -1   1  -1   1  -1   1  -1]]
K[8] = 
[[  1   1   1   1   1   1   1   1   1]
 [  8   6   4   2   0  -2  

In [129]:
N=4
K=krav(N)
B=np.diag([int(special.binom(N,i)) for i in range(N+1)])
S=dot(K,B)
print(not numpy.any(S-S.T))
e=eig(S)
e[0]

True


array([-16.,  -8.,   6.,   8.,  16.])

In [130]:
N=4
X=krav(N)
Y=np.multiply(X,X)
X,sum(Y,axis=0),sum(Y,axis=1)

(array([[ 1,  1,  1,  1,  1],
        [ 4,  2,  0, -2, -4],
        [ 6,  0, -2,  0,  6],
        [ 4, -2,  0,  2, -4],
        [ 1, -1,  1, -1,  1]]),
 array([70, 10,  6, 10, 70]),
 array([ 5, 40, 76, 40,  5]))

In [131]:
rr=range(N+1)
[special.binom(2*N-2*j,N-j)*special.binom(2*j,j)/special.binom(N,j) for j in rr]

[70.0, 10.0, 6.0, 10.0, 70.0]

In [132]:
mm=range(int(N/2)+1)
[sum(special.binom(N+1,2*k+1)*special.binom(2*k,k)*special.binom(N-2*k,m-k) for k in range(m+1))for m in mm]

[5.0, 40.0, 76.0]