In [22]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [23]:
from sympy import *

In [24]:
init_printing()

In [25]:
def krav(N):
    K=np.zeros((N+1,N+1),dtype=int)
    for i in range(N+1):
        K[i,N]=int(binomial(N,i)*(-1)**i)
        K[0,i]=1

    for i in range(1,N+1):
        for j in range(N,0,-1):
            K[i,j-1]=K[i-1,j-1]+K[i-1,j]+K[i,j]
    return K            

In [26]:
 for N in range(1,13):
     K =krav(N)
     y="K["+str(N)+"] = "
     print(y)
     print(K)

K[1] = 
[[ 1  1]
 [ 1 -1]]
K[2] = 
[[ 1  1  1]
 [ 2  0 -2]
 [ 1 -1  1]]
K[3] = 
[[ 1  1  1  1]
 [ 3  1 -1 -3]
 [ 3 -1 -1  3]
 [ 1 -1  1 -1]]
K[4] = 
[[ 1  1  1  1  1]
 [ 4  2  0 -2 -4]
 [ 6  0 -2  0  6]
 [ 4 -2  0  2 -4]
 [ 1 -1  1 -1  1]]
K[5] = 
[[  1   1   1   1   1   1]
 [  5   3   1  -1  -3  -5]
 [ 10   2  -2  -2   2  10]
 [ 10  -2  -2   2   2 -10]
 [  5  -3   1   1  -3   5]
 [  1  -1   1  -1   1  -1]]
K[6] = 
[[  1   1   1   1   1   1   1]
 [  6   4   2   0  -2  -4  -6]
 [ 15   5  -1  -3  -1   5  15]
 [ 20   0  -4   0   4   0 -20]
 [ 15  -5  -1   3  -1  -5  15]
 [  6  -4   2   0  -2   4  -6]
 [  1  -1   1  -1   1  -1   1]]
K[7] = 
[[  1   1   1   1   1   1   1   1]
 [  7   5   3   1  -1  -3  -5  -7]
 [ 21   9   1  -3  -3   1   9  21]
 [ 35   5  -5  -3   3   5  -5 -35]
 [ 35  -5  -5   3   3  -5  -5  35]
 [ 21  -9   1   3  -3  -1   9 -21]
 [  7  -5   3  -1  -1   3  -5   7]
 [  1  -1   1  -1   1  -1   1  -1]]
K[8] = 
[[  1   1   1   1   1   1   1   1   1]
 [  8   6   4   2   0  -2  

In [27]:
N=5
K=krav(N)
B=np.diag([int(binomial(N,i)) for i in range(N+1)])
S=dot(K,B)
print(not numpy.any(S-S.T))
e=eig(S)
e[0]

True


array([-40.63218034,  40.63218034, -19.10843053, -11.65734975,
        11.65734975,  19.10843053])

In [28]:
N=8
X=krav(N)
Y=np.multiply(X,X)
X,sum(Y,axis=0),sum(Y,axis=1)

(array([[  1,   1,   1,   1,   1,   1,   1,   1,   1],
        [  8,   6,   4,   2,   0,  -2,  -4,  -6,  -8],
        [ 28,  14,   4,  -2,  -4,  -2,   4,  14,  28],
        [ 56,  14,  -4,  -6,   0,   6,   4, -14, -56],
        [ 70,   0, -10,   0,   6,   0, -10,   0,  70],
        [ 56, -14,  -4,   6,   0,  -6,   4,  14, -56],
        [ 28, -14,   4,   2,  -4,   2,   4, -14,  28],
        [  8,  -6,   4,  -2,   0,   2,  -4,   6,  -8],
        [  1,  -1,   1,  -1,   1,  -1,   1,  -1,   1]]),
 array([12870,   858,   198,    90,    70,    90,   198,   858, 12870]),
 array([    9,   240,  2016,  6768, 10036,  6768,  2016,   240,     9]))

In [29]:
rr=range(N+1)
[binomial(2*N-2*j,N-j)*binomial(2*j,j)/binomial(N,j) for j in rr]

In [30]:
mm=range(int(N/2)+1)
[sum(binomial(N+1,2*k+1)*binomial(2*k,k)*binomial(N-2*k,m-k) for k in range(m+1))for m in mm]

In [31]:
binomial(8,4)

In [33]:
krav(4)

array([[ 1,  1,  1,  1,  1],
       [ 4,  2,  0, -2, -4],
       [ 6,  0, -2,  0,  6],
       [ 4, -2,  0,  2, -4],
       [ 1, -1,  1, -1,  1]])