In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
from scipy import special

In [13]:
from IPython.core.display import display,HTML,Math,Latex

In [14]:
def krav(N):
    K=np.zeros((N+1,N+1),dtype=int)
    for i in range(N+1):
        K[i,N]=int(special.binom(N,i)*(-1)**i)
        K[0,i]=1

    for i in range(1,N+1):
        for j in range(N,0,-1):
            K[i,j-1]=K[i-1,j-1]+K[i-1,j]+K[i,j]
    return K            

In [23]:
krav(8)

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  8,   6,   4,   2,   0,  -2,  -4,  -6,  -8],
       [ 28,  14,   4,  -2,  -4,  -2,   4,  14,  28],
       [ 56,  14,  -4,  -6,   0,   6,   4, -14, -56],
       [ 70,   0, -10,   0,   6,   0, -10,   0,  70],
       [ 56, -14,  -4,   6,   0,  -6,   4,  14, -56],
       [ 28, -14,   4,   2,  -4,   2,   4, -14,  28],
       [  8,  -6,   4,  -2,   0,   2,  -4,   6,  -8],
       [  1,  -1,   1,  -1,   1,  -1,   1,  -1,   1]])

In [24]:
N=4
krav(2*N)[N,:]

array([ 70,   0, -10,   0,   6,   0, -10,   0,  70])

In [25]:
B=np.diag([int(special.binom(N,i)) for i in range(N+1)])
S=dot(K,B)
print(not numpy.any(S-S.T))
e=eig(S)
e[0]

True


array([-16.,  -8.,   6.,   8.,  16.])

In [26]:
N=10
sum([special.binom(N,x)**2 for x in range(N+1)]),special.binom(2*N,N)

(184756.0, 184756.0)